### ISSUE TITLE
Code formatting issue with Hydrogen and Playwright

### ISSUE THREAD

**Issue by paulomenezes** [cenfun/remix-with-playwright#1]
Hello, I'm using Playwright to generate test coverage for my project, and I've noticed a strange formatting issue in the React code inside the coverage report. The coverage worked perfectly, but I'm using Hydrogen instead of Remix, and the formatting in my case looks like this:

```tsx
function FeaturedCollection({
    collection,
}: {
    collection: FeaturedCollectionFragment;
}) {
    if (!collection) return null;
    const image = collection?.image;
    return ( <
        Link className = "featured-collection"
        to = {
            `/collections/${collection.handle}`
        } >
        {
            image && ( <
                div className = "featured-collection-image" >
                <
                Image data = {
                    image
                }
                sizes = "100vw" / >
                <
                /div>
            )
        } <
        h1 > {
            collection.title
        } < /h1> <
        /Link>
    );
}
```

The extra spacing and HTML-like formatting are unexpected. Since Hydrogen uses Remix but is not 100% identical, I'm unsure if this is related to the test coverage, source maps, or some other setting I'm missing. Do you have some clue? If you don't have nothing in mind, maybe there is a way to run prettier for each file before running/opening the report.

Thanks in advance!

**Comment by cenfun** [comment]
Did you enabled `Format`?
![image](https://github.com/user-attachments/assets/66e5b79e-dca4-47c3-80a3-e9f00d25cc37)

**Comment by paulomenezes** [comment]
Yes 🤦  
When I started testing my hydrogen project was without a source map so the `Format` was a good solution, but when I figured out the source mapping I didn't bother to disable it because I didn't even think it could be a problem.

Thanks a lot and sorry for the dumb issue, and thank you a lot for the example!
